### ISSUE TITLE
Pass rustls features from futures-rustls

### ISSUE THREAD

**Issue by franfrandev** [rustls/futures-rustls#10]
This crate is using a slightly outdated version of `rustls`, which puts `aws-lc-rs` behind a feature that can only be reached on the "inner" Cargo.toml and it makes the module unusable.
Would it be possible to pass feature to `rustls` directly from `futures-rustls` please ?

**Comment by franfrandev** [comment]
Solved by https://github.com/rustls/futures-rustls/pull/9 but I believe this issue to be still standing

**Comment by jbr** [comment]
I think this is closed by #9?

**Comment by franfrandev** [comment]
yes, thanks a lot for your work @jbr !
