### ISSUE TITLE
Switch to rustls-webpki

### ISSUE THREAD

**Issue by MOZGIII** [rustls/futures-rustls#5]
As per https://rustsec.org/advisories/RUSTSEC-2023-0052 webpki is vulnerable, but it is also unmaintained. Better switch to rustls-webpki.

**Comment by quininer** [comment]
Don't worry, futures-rustls itself does not use webpki crate, it only exists in test dependencies.

**Comment by MOZGIII** [comment]
It also seems like it already uses `rust-webpki`, my bad. I'll have to file an issue with the other dependency of mine, thx!
